name: CI
on: [push, pull_request]

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make wget tar

      - name: Install premake
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xzf premake-5.0.0-beta2-linux.tar.gz
          sudo mv premake5 /usr/local/bin/premake5

      - name: Generate build files
        run: premake5 gmake2

      - name: Build release & debug
        working-directory: build
        run: |
          make config=release
          make config=debug
