name: CI
on: [push, pull_request]

jobs:
  build-fedora:
    runs-on: fedora-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo dnf install -y gcc-c++ make wget tar

      - name: Install premake
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xzf premake-5.0.0-beta2-linux.tar.gz
          sudo mv premake5 /usr/local/bin/

      - name: Generate build files
        run: premake5 gmake2

      - name: Build release & debug
        working-directory: build
        run: make config=release && make config=debug

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++ make wget tar

      - name: Install premake
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xzf premake-5.0.0-beta2-linux.tar.gz
          sudo mv premake5 /usr/local/bin/

      - name: Generate build files
        run: premake5 gmake2

      - name: Build release & debug
        working-directory: build
        run: make config=release && make config=debug

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Install dependencies
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-gcc make wget tar

      - name: Add mingw to PATH
        shell: powershell
        run: echo "::add-path::C:\\msys64\\mingw64\\bin"

      - name: Install premake
        run: |
          wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip -O premake.zip
          tar -xf premake.zip
          move premake5.exe C:\Windows\System32\

      - name: Generate build files
        shell: bash
        run: premake5 gmake2

      - name: Build release & debug
        shell: bash
        run: make config=release && make config=debug
